object fQwertyKey: TfQwertyKey
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = 'Qwerty Keyboard'
  ClientHeight = 469
  ClientWidth = 1005
  Color = 12761254
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnClose = FormClose
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object labPrompt: TLabel
    Left = 8
    Top = 8
    Width = 989
    Height = 24
    AutoSize = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    Transparent = True
  end
  object edContent: TEdit
    Left = 8
    Top = 36
    Width = 989
    Height = 40
    AutoSize = False
    Color = 14670284
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -27
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    OnKeyPress = edContentKeyPress
  end
  object palRange: TPanel
    Left = 8
    Top = 84
    Width = 989
    Height = 48
    BevelOuter = bvNone
    Color = 12761254
    TabOrder = 1
    object labCurrent: TLabel
      Left = 0
      Top = 4
      Width = 84
      Height = 24
      AutoSize = False
      Caption = 'Current'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      Transparent = True
    end
    object labMin: TLabel
      Left = 320
      Top = 4
      Width = 44
      Height = 24
      AutoSize = False
      Caption = 'Min'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      Transparent = True
    end
    object labMax: TLabel
      Left = 640
      Top = 4
      Width = 44
      Height = 24
      AutoSize = False
      Caption = 'Max'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      Transparent = True
    end
    object edCurrent: TEdit
      Left = 84
      Top = 0
      Width = 190
      Height = 32
      AutoSize = False
      Color = 14670284
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 0
    end
    object edMin: TEdit
      Left = 364
      Top = 0
      Width = 190
      Height = 32
      AutoSize = False
      Color = 14670284
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 1
    end
    object edMax: TEdit
      Left = 684
      Top = 0
      Width = 190
      Height = 32
      AutoSize = False
      Color = 14670284
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 2
    end
  end
  object palKeyboardArea: TPanel
    Left = 0
    Top = 144
    Width = 1005
    Height = 300
    BevelOuter = bvNone
    Color = 12761254
    TabOrder = 2
    object palFullKey: TPanel
      Left = 0
      Top = 0
      Width = 725
      Height = 300
      Align = alLeft
      BevelOuter = bvNone
      Color = 12761254
      TabOrder = 0
      object spbKey00: TSpeedButton
        Left = 4
        Top = 0
        Width = 50
        Height = 50
        Caption = '`'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey01: TSpeedButton
        Left = 58
        Top = 0
        Width = 50
        Height = 50
        Caption = '1'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey02: TSpeedButton
        Left = 112
        Top = 0
        Width = 50
        Height = 50
        Caption = '2'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey03: TSpeedButton
        Left = 166
        Top = 0
        Width = 50
        Height = 50
        Caption = '3'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey04: TSpeedButton
        Left = 220
        Top = 0
        Width = 50
        Height = 50
        Caption = '4'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey05: TSpeedButton
        Left = 274
        Top = 0
        Width = 50
        Height = 50
        Caption = '5'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey06: TSpeedButton
        Left = 328
        Top = 0
        Width = 50
        Height = 50
        Caption = '6'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey07: TSpeedButton
        Left = 382
        Top = 0
        Width = 50
        Height = 50
        Caption = '7'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey08: TSpeedButton
        Left = 436
        Top = 0
        Width = 50
        Height = 50
        Caption = '8'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey09: TSpeedButton
        Left = 490
        Top = 0
        Width = 50
        Height = 50
        Caption = '9'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey10: TSpeedButton
        Left = 544
        Top = 0
        Width = 50
        Height = 50
        Caption = '0'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey11: TSpeedButton
        Left = 598
        Top = 0
        Width = 50
        Height = 50
        Caption = '-'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey12: TSpeedButton
        Left = 652
        Top = 0
        Width = 50
        Height = 50
        Caption = '='
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey13: TSpeedButton
        Left = 22
        Top = 56
        Width = 50
        Height = 50
        Caption = 'q'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey14: TSpeedButton
        Left = 76
        Top = 56
        Width = 50
        Height = 50
        Caption = 'w'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey15: TSpeedButton
        Left = 130
        Top = 56
        Width = 50
        Height = 50
        Caption = 'e'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey16: TSpeedButton
        Left = 184
        Top = 56
        Width = 50
        Height = 50
        Caption = 'r'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey17: TSpeedButton
        Left = 238
        Top = 56
        Width = 50
        Height = 50
        Caption = 't'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey18: TSpeedButton
        Left = 292
        Top = 56
        Width = 50
        Height = 50
        Caption = 'y'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey19: TSpeedButton
        Left = 346
        Top = 56
        Width = 50
        Height = 50
        Caption = 'u'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey20: TSpeedButton
        Left = 400
        Top = 56
        Width = 50
        Height = 50
        Caption = 'i'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey21: TSpeedButton
        Left = 454
        Top = 56
        Width = 50
        Height = 50
        Caption = 'o'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey22: TSpeedButton
        Left = 508
        Top = 56
        Width = 50
        Height = 50
        Caption = 'p'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey23: TSpeedButton
        Left = 562
        Top = 56
        Width = 50
        Height = 50
        Caption = '['
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey24: TSpeedButton
        Left = 616
        Top = 56
        Width = 50
        Height = 50
        Caption = ']'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey25: TSpeedButton
        Left = 670
        Top = 56
        Width = 50
        Height = 50
        Caption = '\'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey26: TSpeedButton
        Left = 40
        Top = 112
        Width = 50
        Height = 50
        Caption = 'a'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey27: TSpeedButton
        Left = 94
        Top = 112
        Width = 50
        Height = 50
        Caption = 's'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey28: TSpeedButton
        Left = 148
        Top = 112
        Width = 50
        Height = 50
        Caption = 'd'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey29: TSpeedButton
        Left = 202
        Top = 112
        Width = 50
        Height = 50
        Caption = 'f'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey30: TSpeedButton
        Left = 256
        Top = 112
        Width = 50
        Height = 50
        Caption = 'g'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey31: TSpeedButton
        Left = 310
        Top = 112
        Width = 50
        Height = 50
        Caption = 'h'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey32: TSpeedButton
        Left = 364
        Top = 112
        Width = 50
        Height = 50
        Caption = 'j'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey33: TSpeedButton
        Left = 418
        Top = 112
        Width = 50
        Height = 50
        Caption = 'k'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey34: TSpeedButton
        Left = 472
        Top = 112
        Width = 50
        Height = 50
        Caption = 'l'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey35: TSpeedButton
        Left = 526
        Top = 112
        Width = 50
        Height = 50
        Caption = ';'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey36: TSpeedButton
        Left = 580
        Top = 112
        Width = 50
        Height = 50
        Caption = #39
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey37: TSpeedButton
        Left = 58
        Top = 168
        Width = 50
        Height = 50
        Caption = 'z'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey38: TSpeedButton
        Left = 112
        Top = 168
        Width = 50
        Height = 50
        Caption = 'x'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey39: TSpeedButton
        Left = 166
        Top = 168
        Width = 50
        Height = 50
        Caption = 'c'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey40: TSpeedButton
        Left = 220
        Top = 168
        Width = 50
        Height = 50
        Caption = 'v'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey41: TSpeedButton
        Left = 274
        Top = 168
        Width = 50
        Height = 50
        Caption = 'b'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey42: TSpeedButton
        Left = 328
        Top = 168
        Width = 50
        Height = 50
        Caption = 'n'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey43: TSpeedButton
        Left = 382
        Top = 168
        Width = 50
        Height = 50
        Caption = 'm'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey44: TSpeedButton
        Left = 436
        Top = 168
        Width = 50
        Height = 50
        Caption = ','
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey45: TSpeedButton
        Left = 490
        Top = 168
        Width = 50
        Height = 50
        Caption = '.'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbKey46: TSpeedButton
        Left = 544
        Top = 168
        Width = 50
        Height = 50
        Caption = '/'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbChangeCase: TSpeedButton
        Left = 0
        Top = 224
        Width = 74
        Height = 50
        Caption = 'Case'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnChangeCaseClick
      end
      object spbKey47: TSpeedButton
        Left = 80
        Top = 224
        Width = 360
        Height = 50
        Caption = ' '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbBackspace: TSpeedButton
        Left = 446
        Top = 224
        Width = 50
        Height = 50
        Caption = 'BS'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnBackspaceClick
      end
      object spbClear: TSpeedButton
        Left = 502
        Top = 224
        Width = 50
        Height = 50
        Caption = 'Del'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnClearClick
      end
      object spbCancel: TSpeedButton
        Left = 558
        Top = 224
        Width = 72
        Height = 50
        Caption = 'Abort'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnCancelClick
      end
      object spbOk: TSpeedButton
        Left = 636
        Top = 224
        Width = 88
        Height = 50
        Caption = 'OK'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        OnClick = btnOkClick
      end
    end
    object palNumKey: TPanel
      Left = 725
      Top = 0
      Width = 280
      Height = 300
      Align = alClient
      BevelOuter = bvNone
      Color = 12761254
      TabOrder = 1
      object spbNum7: TSpeedButton
        Left = 4
        Top = 0
        Width = 50
        Height = 50
        Caption = '7'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbNum8: TSpeedButton
        Left = 58
        Top = 0
        Width = 50
        Height = 50
        Caption = '8'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbNum9: TSpeedButton
        Left = 112
        Top = 0
        Width = 50
        Height = 50
        Caption = '9'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbAdd1: TSpeedButton
        Left = 166
        Top = 0
        Width = 50
        Height = 50
        Caption = '+1'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlue
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        OnClick = btnStepClick
      end
      object spbMinus1: TSpeedButton
        Left = 220
        Top = 0
        Width = 50
        Height = 50
        Caption = '-1'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlue
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        OnClick = btnStepClick
      end
      object spbNum4: TSpeedButton
        Left = 4
        Top = 56
        Width = 50
        Height = 50
        Caption = '4'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbNum5: TSpeedButton
        Left = 58
        Top = 56
        Width = 50
        Height = 50
        Caption = '5'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbNum6: TSpeedButton
        Left = 112
        Top = 56
        Width = 50
        Height = 50
        Caption = '6'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbAdd10: TSpeedButton
        Left = 166
        Top = 56
        Width = 50
        Height = 50
        Caption = '+10'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlue
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        OnClick = btnStepClick
      end
      object spbMinus10: TSpeedButton
        Left = 220
        Top = 56
        Width = 50
        Height = 50
        Caption = '-10'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlue
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        OnClick = btnStepClick
      end
      object spbNum1: TSpeedButton
        Left = 4
        Top = 112
        Width = 50
        Height = 50
        Caption = '1'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbNum2: TSpeedButton
        Left = 58
        Top = 112
        Width = 50
        Height = 50
        Caption = '2'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbNum3: TSpeedButton
        Left = 112
        Top = 112
        Width = 50
        Height = 50
        Caption = '3'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbAdd100: TSpeedButton
        Left = 166
        Top = 112
        Width = 50
        Height = 50
        Caption = '+100'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlue
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        OnClick = btnStepClick
      end
      object spbMinus100: TSpeedButton
        Left = 220
        Top = 112
        Width = 50
        Height = 50
        Caption = '-100'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlue
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        OnClick = btnStepClick
      end
      object spbNum0: TSpeedButton
        Left = 4
        Top = 168
        Width = 50
        Height = 50
        Caption = '0'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnKeyClick
      end
      object spbDecimal: TSpeedButton
        Left = 58
        Top = 168
        Width = 50
        Height = 50
        Caption = '.'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnDecimalClick
      end
      object spbMinus: TSpeedButton
        Left = 112
        Top = 168
        Width = 50
        Height = 50
        Caption = '+/-'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnMinusClick
      end
      object spbStepMode: TSpeedButton
        Left = 166
        Top = 168
        Width = 104
        Height = 50
        Caption = 'Step'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnDecimalModeClick
      end
      object spbNumBackspace: TSpeedButton
        Left = 4
        Top = 236
        Width = 50
        Height = 50
        Caption = 'BS'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnBackspaceClick
      end
      object spbNumClear: TSpeedButton
        Left = 58
        Top = 236
        Width = 50
        Height = 50
        Caption = 'Del'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnClearClick
      end
      object spbNumCancel: TSpeedButton
        Left = 112
        Top = 236
        Width = 50
        Height = 50
        Caption = 'Abort'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        OnClick = btnCancelClick
      end
      object spbNumOk: TSpeedButton
        Left = 166
        Top = 236
        Width = 104
        Height = 50
        Caption = 'OK'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        OnClick = btnOkClick
      end
    end
  end
end
